### PR TITLE
Retry fix for unsafe initialization in graph classes

### LINKED ISSUE #269: Unsafe Constant Initialization
In `ignition::math::Color` the color constants are defined like `public: static const Color Cyan;`. While the resulting interface is nice to use, it could cause static initialization order fiasco as C++ makes no guarantee that global variables in this form is going to be initialized in usage order. In other words, another global variable could use `Color::Cyan` and be initialized first.

A simple fix is to convert to a function form like the following:
`public: const Color& Cyan() { static auto *c = new Color(0, 1, 1, 1); return *c; }`

Another solution is more involved but it could retain the ability to refer to constants without parentheses.
1. Add a constexpr constructor to the class.
2. In another class, say, ColorConstants, use `public: static constexpr Color Cyan = {0, 1, 1, 1};`

Both solutions represent a API/ABI change, so I would like to hear some feedback first before sending out PRs.

The Vector classes might be affected by this too.

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes #269.

## Summary

The is a second attempt at fixing the potentially unsafe initialization issues in the `graph::Edge` and `graph::Vertex` classes after the first attempt in #606 was reverted in #609 due to test failures that it caused in gz-sim (documented in https://github.com/osrf/buildfarm-tools/issues/67#issuecomment-2232120738). This pull request uses a static local variable instead of dynamic memory allocation and doesn't cause gz-sim test failures in my testing.

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [X] Updated migration guide (as needed)
- [X] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
using the `ci_matching_branch/` technique with https://github.com/osrf/homebrew-simulation/commit/e682b2596e6cd40dc8be3c4a8414818a1c3f16ca and https://github.com/gazebosim/gz-sim/pull/2482, this branch and https://github.com/gazebosim/sdformat/pull/1460 are test in gz-sim CI:

* [Build Status](https://build.osrfoundation.org/job/gz_sim-ci-pr_any-homebrew-amd64/649/) https://build.osrfoundation.org/job/gz_sim-ci-pr_any-homebrew-amd64/649/

**Review by ahcorde — APPROVED** [review]

File: include/gz/math/graph/Edge.hh [hunk 1]
```diff
@@ -330,9 +333,19 @@ namespace graph
...
+  // Deprecated in favor of NullEdge().
   template<typename E>
   DirectedEdge<E> DirectedEdge<E>::NullEdge(
     VertexId_P(kNullId, kNullId), E(), 1.0, kNullId);
+
+  /// \brief An invalid edge.
+  template<typename E, typename EdgeType>
+  EdgeType &NullEdge()
+  {
+    static EdgeType e(
```
Comment (azeey) [inline include/gz/math/graph/Edge.hh:345]: This is still problematic depending the given types `E`, and `EdgeType` because the destructor eventually runs when the program exits. According to the [Google style guide](https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables), it's best to allocate memory from the heap and never delete it, which will avoid calling the destructor. `gz::utils::NeverDestroyed` does exactly that, so I recommend we switch to that.

**Review by azeey — CHANGES_REQUESTED** [review]

File: include/gz/math/graph/Edge.hh (hunk 1 above)
Comment (scpeters) [reply include/gz/math/graph/Edge.hh]: trying `NeverDestroyed` in https://github.com/gazebosim/gz-math/pull/612/commits/3fa98549b1e781aca2f17909538c4891548963ad

Comment (scpeters) [reply include/gz/math/graph/Edge.hh]: rerunning gz-sim CI [Build Status](https://build.osrfoundation.org/job/gz_sim-ci-pr_any-homebrew-amd64/693/) https://build.osrfoundation.org/job/gz_sim-ci-pr_any-homebrew-amd64/693/

**Review by azeey — APPROVED** [review]
