### PR TITLE
Fix potential unsafe initialization in the Graph class

### LINKED ISSUE #269: Unsafe Constant Initialization
In `ignition::math::Color` the color constants are defined like `public: static const Color Cyan;`. While the resulting interface is nice to use, it could cause static initialization order fiasco as C++ makes no guarantee that global variables in this form is going to be initialized in usage order. In other words, another global variable could use `Color::Cyan` and be initialized first.

A simple fix is to convert to a function form like the following:
`public: const Color& Cyan() { static auto *c = new Color(0, 1, 1, 1); return *c; }`

Another solution is more involved but it could retain the ability to refer to constants without parentheses.
1. Add a constexpr constructor to the class.
2. In another class, say, ColorConstants, use `public: static constexpr Color Cyan = {0, 1, 1, 1};`

Both solutions represent a API/ABI change, so I would like to hear some feedback first before sending out PRs.

The Vector classes might be affected by this too.

### PR DESCRIPTION
**Pull request by caguero**
# 🦟 Bug fix

Partially fixes #269 (`Graph` class).

## Summary

I implemented the "Construct on first use" idiom (https://www.freecodecamp.org/news/cpp-static-initialization-order-fiasco/) to avoid the potential unsafe construction.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

File: include/gz/math/graph/Graph.hh [hunk 1]
```diff
@@ -150,7 +150,7 @@ namespace graph
         {
           std::cerr << "[Graph::AddVertex()] The limit of vertices has been "
                     << "reached. Ignoring vertex." << std::endl;
-          return Vertex<V>::NullVertex;
+          return NullVertex<V>();
```
Comment (scpeters) [inline include/gz/math/graph/Graph.hh:153]: this seems like an API change; we may need to do it, but let me check if sdformat will be affected

Comment (scpeters) [reply include/gz/math/graph/Graph.hh:153]: yes, this will require changes in sdformat:

https://github.com/gazebosim/sdformat/blob/main/src/FrameSemantics.cc#L89

File: include/gz/math/graph/Edge.hh [hunk 2]
```diff
@@ -204,9 +205,6 @@ namespace graph
   template<typename E>
   class UndirectedEdge : public Edge<E>
   {
-    /// \brief An invalid undirected edge.
-    public: static UndirectedEdge<E> NullEdge;
```
Comment (scpeters) [inline include/gz/math/graph/Edge.hh:208]: We may choose to make a hard API break here, but I'd prefer to not remove these static types in this pull request, but to deprecate them instead, so that we can coordinate fixes for sdformat and any other `gz-*` packages in separate pull requests.

**Review by scpeters — CHANGES_REQUESTED** [review]
we should update the migration guide to document the API break / deprecation, depending on which route we take

**Comment by caguero** [comment]
> we should update the migration guide to document the API break / deprecation, depending on which route we take

Migration guide updated. See [15b8975](https://github.com/gazebosim/gz-math/pull/606/commits/15b8975131bdef5f44c7932f4d120a15d21eca64) and [5f606f0](https://github.com/gazebosim/gz-math/pull/606/commits/5f606f0b6acfc11ec94ad077f7ea7229cd8ee44e).

File: include/gz/math/graph/Graph.hh (hunk 1 above)
Comment (caguero) [reply include/gz/math/graph/Graph.hh:153]: I restored the original static members and added deprecations. It should be possible to keep using them.
[15b8975](https://github.com/gazebosim/gz-math/pull/606/commits/15b8975131bdef5f44c7932f4d120a15d21eca64)

File: include/gz/math/graph/Edge.hh (hunk 2 above)
Comment (caguero) [reply include/gz/math/graph/Edge.hh:208]: Let me know if the changes in  [15b8975](https://github.com/gazebosim/gz-math/pull/606/commits/15b8975131bdef5f44c7932f4d120a15d21eca64) are sufficient to keep sdformat and friends compiling.

Comment (scpeters) [reply include/gz/math/graph/Edge.hh:208]: it looks like sdformat15 will still compile with this change as of https://github.com/gazebosim/gz-math/pull/606/commits/5f606f0b6acfc11ec94ad077f7ea7229cd8ee44e (tested using the `ci_matching_branch/` trick partially documented in https://github.com/gazebosim/docs/pull/377)

[Build Status](https://build.osrfoundation.org/view/gz-ionic/job/sdformat15-install_bottle-homebrew-amd64/210/) https://build.osrfoundation.org/view/gz-ionic/job/sdformat15-install_bottle-homebrew-amd64/210/

File: Migration.md [hunk 3]
```diff
@@ -5,6 +5,32 @@ Deprecated code produces compile-time warnings. These warning serve as
...
+
+1. **graph/Graph.hh**
+    + The functions `Graph::AddVertex()` and `Graph::VertexFromId()` might
+      return NullVertex() instead of NullVertex.
+      E.g.: https://github.com/gazebosim/gz-math/pull/606/files#diff-0c0220a7e72be70337975433eeddc3f5e072ade5cd80dfb1ac03da233c39c983L153-R153
+
+    + The functions `Graph::AddEdge()`, `Graph::LinkEdge()`,
+      `Graph::EdgeFromVertices()` and `Graph::EdgeFromId()` functions might
+      return NullEdge() instead of NullEdge.
+      E.g.: https://github.com/gazebosim/gz-math/pull/606/files#diff-0c0220a7e72be70337975433eeddc3f5e072ade5cd80dfb1ac03da233c39c983L222-R222
```
Comment (scpeters) [inline Migration.md:20]: I don't think these are breaking change in `Graph.hh`. I had originall commented on `Graph.hh` because that is where I noticed that our API was changing due to the previously removed type, but for this PR, I think the only needed change to the Migration guide is the deprecations below

File: Migration.md [hunk 4]
```diff
@@ -5,6 +5,32 @@ Deprecated code produces compile-time warnings. These warning serve as
...
+
```
Comment (scpeters) [inline Migration.md:21]:
```suggestion
```

File: Migration.md (hunk 3 above)
Comment (caguero) [reply Migration.md]: You're right, we're not changing the function signature so it should be fine.

File: include/gz/math/graph/Edge.hh [hunk 5]
```diff
@@ -332,9 +336,19 @@ namespace graph
...
   DirectedEdge<E> DirectedEdge<E>::NullEdge(
     VertexId_P(kNullId, kNullId), E(), 1.0, kNullId);
+
+  /// \brief An invalid edge.
+  template<typename E, typename EdgeType>
+  EdgeType &NullEdge()
+  {
+    static auto e = std::make_unique<EdgeType>(
+      VertexId_P(kNullId, kNullId), E(), 1.0, kNullId);
+    return *e;
```
Comment (scpeters) [inline include/gz/math/graph/Edge.hh:350]: looking at [Material::Predefined()](https://github.com/gazebosim/gz-math/blob/0ebc06e80adb5d3359957dd0d9b6b5e9d08013c2/src/Material.cc#L98-L119), I wonder if the unique pointer should be made and released from inside a static lambda function?

Comment (azeey) [reply include/gz/math/graph/Edge.hh:350]: I think it would be better to use `gz::utils::NeverDestroyed` (e.g. https://github.com/gazebosim/sdformat/blob/f05f4e7ad1a6784f9ff1a6c1b362191677baa70d/src/Types.cc#L149). However, the fact that this function returns a non-const reference could be problematic since anyone can modify the value.

Comment (scpeters) [reply include/gz/math/graph/Edge.hh:350]: regarding the non-const reference, I think the behavior in gz-math7 and earlier with static variables has a similar issue right? I tried changing the `NullEdge` and `NullVertex` functions to return a const reference, but lots of `Graph.hh` functions that currently return non-const references like to return references to `NullEdge` or `NullVertex` and fail to compile. This seems like a bigger issue with the API that we could open an issue about.

Comment (scpeters) [reply include/gz/math/graph/Edge.hh:350]: trying again in https://github.com/gazebosim/gz-math/pull/612
